default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "postgres" %>
  host: <%= ENV["DB_HOST"] || "db" %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "team_dynamics_app_development" %>

test:
  <<: *default
  database: team_dynamics_app_test

production:
  primary: &primary_production
    <<: *default
    database: team_dynamics_app_production
    username: team_dynamics_app
    password: <%= ENV["TEAM_DYNAMICS_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: team_dynamics_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: team_dynamics_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: team_dynamics_app_production_cable
    migrations_paths: db/cable_migrate
